# -*- coding: utf-8 -*-
"""THDLearningBuoi1Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciJdqtk_Ld4LkoaBP-03t3fsgcjHHZaB

3. Tạo Numpy array

3.1 Tạo aray 1-chiều
"""

import numpy as np
from os.path import normpath

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# chuyển list --> Numpy array
# Đã sửa lỗi bằng cách thêm 'import numpy as np'
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

"""3.2 Array 2-chiều"""

import numpy as np
c = np.array([(1,2,3),
              (4,5,6)
              ])
print(c)
print(c.shape)
print(c.dtype)

"""3.3 Array 3 chiều"""

import numpy as np
d = np.array([
              [[1.,2.,3.], [4.,5., 6.]],
              [[7.,8.,9.],[10,11,12]]
])
print(d)
print(d.shape)
print(d.dtype)

"""3.4 Tạo Array với giá trị ban đầu là 0 hoặc 1"""

import numpy as np
e = np.zeros((2, 2))
f = np.ones ((3, 3 ))
print('Zero maxtrix:\n', e)
print('One maxtrix:\n', f)

"""3.5 Reshape và flatten ma trận

3.5.1 reshape thay đổi kích thước ma trận
"""

import numpy as np

e = np.array([(1.,2.,3.), (4.,5.,6.)])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g = np.array([[[1.,2.,3.],[4.,5.,6.]],
              [[7.,8.,9.],[10.,11.,12.]]
              ])
print(g)
print(g.shape)
h= g.reshape(3,4)
print('reshape (3,4)\n',h)
j =g.reshape(3,2,2)
print('reshape (3,2,2)\n',j)
k = g.reshape(2,2,3)
print('reshape (2,2,3)\n',k)

"""3.5.2. Platten là chuyển array nhiều chiều về 1 chiều"""

import numpy as np
e = np.array([[1.,2.,3.], [4.,5.,6.]])
f = e.flatten()
print(f)
g = np.array ([[[1.,2.,3.], [4.,5.,6.]],
              [[7.,8.,9.], [10., 11., 12.]]
               ])
j=g.flatten()
print(j)

"""3.6 Thêm dòng dữ liễu với hstack và vstack"""

import numpy as np
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])
h_stack = np.hstack((f, g))
print('Horizontal Append\n',h_stack)
v_stack = np.vstack((f, g))
print('Vertical Append\n',v_stack)

"""3.7 Sinh mảng số ngẫu nhiên

3.7.1 Sinh mảng số nguyên ngẫu nhiên
"""

import numpy as np

a= np.random.randint(100, size=(5,))
print('Random 1-D array\n', a)
b= np.random.randint(100, size=(3,4))
print('Random 2-D array\n', b)
c = np.random.randint(100, size=(3,4,3))
print('Random 3-D array\n', c)

"""3.7.2 Sinh mảng số thực trong khoảng [0,1]"""

import numpy as np

a= np.random.rand(5)
print('Random 1-D array\n', a)
b= np.random.rand(3,4)
print('Random 2-D array\n', b)
c = np.random.rand(3,4,3)
print('Random 3-D array\n', c)

"""3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian"""

import numpy as np
a = np.random.normal(5, 0.5,10)
print( a)

"""3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

"""

# sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
import numpy as np
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

# sinh ma trận 3 x 5 từ mảng cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

"""3.8. Thay đổi giá trị của ma trận

"""

import numpy as np

A = np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2]=2
print('Change value of third row with array\n',A)
np.asarray(A)[2]=2
print('Change value of third row with asarray\n',A)

"""3.9. Sinh dãy số theo khoảng cho trước

3.9.1. Dùng hàm arange
"""

import numpy as np

# tạo 20 số nguyên từ 1 --> (n-1)
a = np.arange(1, 20)
print(a)

# tạo các số nguyên từ 1 --> (n-1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

"""3.9.2. Dùng hàm linspace"""

import numpy as np

# tạo 10 số thực trong khoảng từ 1.0 đến 5.0
a = np.linspace(1., 5., num=10)
print(a)

"""3.10. Index và slice"""

import numpy as np

# slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('first row:', a[0])
print('second row:', a[1])

# indexing
print('Second column:', a[:, 1])
print('first column', a[:, 0])
print('First two values of second row:', a[1, :2])

"""**PANDAS**

5. Cài đặt PANDAS
"""

pip install pandas

"""6. TÌM HIỂU ĐỐI TƯỢNG SERIES

Series là cấu trúc dữ liệu 1-chiều
"""

import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value:', a[0])

# Tạo pandas series với chỉ mục (index) tùy chỉnh
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

#tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

"""7. TẠO ĐỐI TƯỢNG DATAFRAME

Chuyển đổi từ mảng dạng Numpy sang Pandas và ngược lại
"""

import numpy as np

# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame: \n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy array: \n', numpy_h)

"""Tạo DataFrame mảng 2-chiều có tên cột"""

# Tạo từ dictionary
dic = {'Name': ['John', 'Smith'], 'Age': [30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

# Tạo mảng ngẫu nhiên 20x4 và đặt tên cột
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) # In 5 dòng đầu tiên

#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head()) #in 5 dòng đầu tiên
#chọn 1 cột
print('chọn 1 cột: \n', df['so1'])
#chọn nhiều dòng
print('chọn nhiều dòng: \n', df[1:3])
#chọn nhiều cột
print('chọn nhiều cột: \n', df[['so1', 'so2']])
#xóa nhiều dòng, nhiều cột
print('xóa nhiều dòng, nhiều cột: \n', df.drop([1, 2]))
#xóa cột
df = df.drop(columns=['so1', 'so2'])
print(df)

"""7.1. Nối nhiều DataFram"""

df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'],
                    'Age': [25, 30, 50]},
                   index=[0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'],
                    'Age': [28, 30]},
                   index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concatenate Two DataFrame:\n', df_concat)
#xóa dòng giá trị trùng lặp theo tên
print('Drop duplicates:\n', df_concat.drop_duplicates('Name'))
#sắp xếp theo cột age
print('Sort values:\n', df_concat.sort_values('Age'))
#đổi tên cột
df_rename = df_concat.rename(columns={'Name': 'Surname', 'Age': 'Age_updated'})
print('Rename columns:\n', df_rename)

"""7.2. Đọc dữ liệu từ CSV"""

#Gom nhóm dữ liệu trong DataFrame
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

"""**BÀI TẬP**

BÀI 1
"""

import numpy as np

# Tạo mảng số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]
arr1 = np.random.randint(0, 21, size=(3, 3))
print(arr1)

# Kiểm tra tất cả các phần tử trong mảng khác 0 bằng hàm all
check_all = np.all(arr1 != 0)
print('Tất cả các phần tử đều khác 0:', check_all)

"""BÀI 2"""

# Tạo mảng số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]
arr2 = np.random.randint(0, 21, size=(3, 3))
print(arr2)

# Kiểm tra tồn tại một phần tử trong mảng khác 0 bằng hàm any
check_any = np.any(arr2 != 0)
print('Tồn tại phần tử khác 0:', check_any)

"""BÀI 3"""

# Khởi tạo dữ liệu mảng 1 chiều và 2 chiều để so sánh
a1 = np.array([1, 5, 10])
b1 = np.array([5, 5, 5])
a2 = np.array([[1, 2], [5, 6]])
b2 = np.array([[2, 2], [5, 5]])

# So sánh
print('greater (1D):', np.greater(a1, b1))
print('greater_equal (1D):', np.greater_equal(a1, b1))
print('less (2D):\n', np.less(a2, b2))
print('less_equal (2D):\n', np.less_equal(a2, b2))

"""BÀI 4"""

# Tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5
arr4 = np.concatenate((np.ones(10), np.zeros(10), np.full(10, 5)))
print(arr4)

"""BÀI 5"""

# Tạo mảng số nguyên chẵn từ [30, 70]
arr5 = np.arange(30, 71, 2)
print(arr5)

"""BÀI 6"""

# Tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, còn lại bằng 0)
arr6 = np.identity(3)
print(arr6)

"""BẢI 7"""

import numpy as np

# Tạo mảng 10 phần tử số nguyên ngẫu nhiên trong khoảng [15, 55]
arr7 = np.random.randint(15, 56, size=10)
print('Mảng ban đầu:', arr7)

# Cắt mảng từ vị trí thứ 1 đến kế cuối (bỏ 0 và -1)
print('Mảng ngoại trừ phần tử đầu và cuối:', arr7[1:-1])

"""BÀI 8"""

# Tạo mảng 20 phần tử trong khoảng [0, 20]
arr8 = np.random.randint(0, 21, size=20)
print('Mảng ban đầu:\n', arr8)

# Tìm và đổi dấu các số nằm trong khoảng [9, 15]
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1
print('Mảng sau khi đổi dấu:\n', arr8)

"""BÀI 9"""

# Tạo ma trận 3x4 với các giá trị ngẫu nhiên trong khoảng [10, 21]
arr9 = np.random.randint(10, 22, size=(3, 4))
print(arr9)

"""BÀI 10"""

# Tạo ma trận 10x10 toàn số 1
arr10 = np.ones((10, 10))

# Gán các phần tử bên trong (bỏ dòng/cột đầu và cuối) thành 0
arr10[1:-1, 1:-1] = 0
print(arr10)

"""BÀI 11"""

# Tạo ma trận 5x5 với đường chéo chính là [1, 2, 3, 4, 5]
arr11 = np.diag([1, 2, 3, 4, 5])
print(arr11)

"""BÀI 12"""

# Tạo mảng 3x3x3 ngẫu nhiên
arr12 = np.random.randint(1, 10, size=(3, 3, 3))
print('Mảng 3x3x3:\n', arr12)

# Tính tổng theo từng trục
print('\nTổng theo trục 0 (các khối ma trận):\n', np.sum(arr12, axis=0))
print('\nTổng theo trục 1 (tổng các cột trong mỗi khối):\n', np.sum(arr12, axis=1))
print('\nTổng theo trục 2 (tổng các dòng trong mỗi khối):\n', np.sum(arr12, axis=2))

"""BÀI 13"""

# Tạo 2 vector ngẫu nhiên 10 phần tử
vec1 = np.random.randint(1, 10, size=10)
vec2 = np.random.randint(1, 10, size=10)

print('Vector 1:', vec1)
print('Vector 2:', vec2)

# Thực hiện inner product
inner_product = np.dot(vec1, vec2)
print('Kết quả np.dot:', inner_product)

"""BÀI 14"""

# Tạo ma trận A (4x3) và vector y (3 phần tử)
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)

print('Ma trận A:\n', A)
print('\nVector y:', y)

# Numpy tự động cộng vector y vào từng dòng của ma trận A
result = A + y
print('\nKết quả ma trận A sau khi thêm vector y vào từng dòng:\n', result)

"""BÀI 15"""

import pandas as pd

# Khởi tạo 2 Series
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng 2 Series:\n", s1 + s2)
print("\nTrừ 2 Series:\n", s1 - s2)
print("\nNhân 2 Series:\n", s1 * s2)
print("\nChia 2 Series:\n", s1 / s2)

"""BÀI 16"""

import pandas as pd

# Tạo DataFrame giống như trong hình
data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(data)
print("DataFrame ban đầu:\n", df)

# Dùng iloc để lấy tất cả các dòng (:) của cột đầu tiên (chỉ số 0)
s_col1 = df.iloc[:, 0]
print("\n1st column as a Series:\n", s_col1)

"""BÀI 17"""

import pandas as pd
import numpy as np

# Tạo DataFrame 4x3 ngẫu nhiên (giá trị từ 0 đến 50)
df_random = pd.DataFrame(np.random.randint(0, 51, size=(4, 3)), columns=['Col_1', 'Col_2', 'Col_3'])
print("DataFrame ban đầu:\n", df_random)

# Sắp xếp DataFrame dựa trên giá trị của 'Col_1' (tăng dần)
df_sorted = df_random.sort_values(by='Col_1')
print("\nDataFrame sau khi sắp xếp theo 'Col_1':\n", df_sorted)

"""BÀI 18"""

import pandas as pd

# Khởi tạo Series ban đầu với index chữ cái
s = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print("Original Data Series:")
print(s)

# Thay đổi thứ tự index bằng hàm reindex
s_reindexed = s.reindex(index=['B', 'A', 'C', 'D', 'E'])
print("Data Series after changing the order of index:")
print(s_reindexed)

"""BÀI 19"""

import pandas as pd

# Khởi tạo 2 Series như trong đề bài
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)

# Lọc các phần tử của sr1 KHÔNG nằm trong sr2
result = sr1[~sr1.isin(sr2)]

print("\nItems of sr1 not present in sr2:")
print(result)

"""BÀI 20"""

import pandas as pd
import numpy as np

# Tạo 2 Series x, y ngẫu nhiên gồm 20 phần tử (giá trị từ 1 đến 30 để dễ thấy điểm giao)
x = pd.Series(np.random.randint(1, 31, size=20))
y = pd.Series(np.random.randint(1, 31, size=20))

print("Series x (20 phần tử):\n", x.values)
print("\nSeries y (20 phần tử):\n", y.values)

# Tìm Hội (Union) - Tất cả các phần tử duy nhất xuất hiện trong x hoặc y
union_xy = np.union1d(x, y)
print("\nHội (Union) của x và y:\n", union_xy)

# Tìm Giao (Intersection) - Các phần tử xuất hiện ở CẢ x và y
intersect_xy = np.intersect1d(x, y)
print("\nGiao (Intersection) của x và y:\n", intersect_xy)

"""BÀI 21"""

import pandas as pd

# Khởi tạo Series x (từ 0 đến 9) và Series y (từ 'p' đến 'y')
x = pd.Series(range(10))
y = pd.Series(list('pqrstuvwxy'))

# Thêm theo chiều dọc (Vertical) -> axis=0
# Dùng ignore_index=True để reset lại index từ 0 -> 19 thay vì lặp lại index cũ
vertical_concat = pd.concat([x, y], axis=0, ignore_index=True)
print("Thêm theo chiều dọc (Vertical):\n", vertical_concat)

# Thêm theo chiều ngang (Horizontal) -> axis=1 (Tạo thành DataFrame)
horizontal_concat = pd.concat([x, y], axis=1)
print("\nThêm theo chiều ngang (Horizontal):\n", horizontal_concat)



"""BÀI 22 -30"""

import pandas as pd
import numpy as np

# --- BÀI 22: Tạo và hiển thị DataFrame ---
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print("--- Bài 22: DataFrame ban đầu ---")
print(df)

# --- BÀI 23: Cho biết 3 dòng đầu tiên ---
print("\n--- Bài 23: 3 dòng đầu tiên ---")
print(df.head(3))

# --- BÀI 24: Chọn cột 'name' và 'score' ---
print("\n--- Bài 24: Cột 'name' và 'score' ---")
print(df[['name', 'score']])

# --- BÀI 25: Chọn những dòng có attempts > 2 ---
print("\n--- Bài 25: Số lần thử (attempts) > 2 ---")
print(df[df['attempts'] > 2])

# --- BÀI 26: Cho biết số dòng, số cột của DataFrame ---
print("\n--- Bài 26: Kích thước DataFrame ---")
print("Số dòng:", df.shape[0])
print("Số cột:", df.shape[1])

# --- BÀI 27: Những dòng có score là NaN ---
print("\n--- Bài 27: Dòng có điểm (score) là NaN ---")
print(df[df['score'].isnull()])

# --- BÀI 28: Những dòng có score trong khoảng (15, 20) ---
# Mặc định hàm between(15, 20) là lấy cả giá trị 15 và 20 (inclusive)
print("\n--- Bài 28: Điểm trong khoảng (15, 20) ---")
print(df[df['score'].between(15, 20)])

# --- BÀI 29: attempts > 2 và score trong khoảng (15, 20) ---
print("\n--- Bài 29: attempts > 2 VÀ score trong khoảng (15, 20) ---")
print(df[(df['attempts'] > 2) & df['score'].between(15, 20)])

# --- BÀI 30: Thay đổi giá trị dòng 'd', cột score là 19 ---
print("\n--- Bài 30: Đổi điểm dòng 'd' thành 19 ---")
df.loc['d', 'score'] = 19
print(df.loc[['d']]) # In ra dòng 'd' để kiểm tra kết quả

