# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/httrung0308/0f5e47e80461fd88d660e6566611c5cf/untitled1.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Đọc file dữ liệu (chú ý tên file phải đúng với file bạn đã upload)
df = pd.read_csv('sample_data/dulieuxettuyendaihoc.csv')

# Xem nhanh 5 dòng đầu
display(df.head())

# Kiểm tra tổng số lượng dữ liệu bị thiếu ở từng cột
print(df.isnull().sum())

# Điền khuyết dữ liệu cột DT bằng giá trị 0
df['DT'] = df['DT'].fillna(0)
# Kiểm tra lại xem còn thiếu không
print("Sau khi xử lý, số dòng thiếu của DT:", df['DT'].isnull().sum())

# Ví dụ: Vẽ Boxplot cho cột điểm khối thi DH1, DH2, DH3 để tìm outlier
plt.figure(figsize=(10, 5))
sns.boxplot(data=df[['DH1', 'DH2', 'DH3']])
plt.title("Biểu đồ Boxplot cho các điểm thi đại học")
plt.show()

# Lấy các cột dữ liệu là số
numeric_cols = df.select_dtypes(include=[np.number]).columns

# Loại trừ cột STT (Số thứ tự) và DT (Dân tộc) ra khỏi việc quét outlier
cols_to_check = [col for col in numeric_cols if col not in ['STT', 'DT']]

for col in cols_to_check:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Lọc bỏ các dòng chứa giá trị nằm ngoài khoảng an toàn
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print("Số lượng dòng còn lại sau khi loại bỏ outlier:", df.shape[0])

# Kiểm tra phân bố của biến Giới tính (GT) và Khối thi (KT)
fig, ax = plt.subplots(1, 2, figsize=(12, 4))
sns.countplot(x='GT', data=df, ax=ax[0])
ax[0].set_title("Phân bố Giới tính (GT)")

sns.countplot(x='KT', data=df, ax=ax[1])
ax[1].set_title("Phân bố Khối thi (KT)")

plt.show()

print("Số lượng đếm từng Khối thi:\n", df['KT'].value_counts())

# 1. Đổi Giới tính (GT): F (Nữ) -> 0, M (Nam) -> 1 bằng Label Encoding
df['GT'] = df['GT'].map({'F': 0, 'M': 1})

# 2. Đổi Khu vực (KV) và Khối thi (KT) bằng One-Hot Encoding
# (Vì các hạng mục này không có tính thứ bậc lớn bé)
df = pd.get_dummies(df, columns=['KV', 'KT'], drop_first=False)

# Chuyển đổi các cột True/False sinh ra từ get_dummies về 0/1 (int)
for col in df.columns:
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)

# Xem thành quả cuối cùng
display(df.head())

"""----------------------------------------------------------"""

# --- 3. MỐI QUAN HỆ GIỮA CÁC BIẾN (Correlation & Heatmap) ---
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Tính ma trận hiệp phương sai (Covariance)
print("--- Ma trận Hiệp phương sai (Covariance) ---")
print(df[['T5', 'T6', 'DH1', 'DH2', 'DH3']].cov())

# Tính ma trận tương quan (Correlation) và vẽ Heatmap
plt.figure(figsize=(8, 6))
corr_matrix = df[['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'DH1']].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("HEATMAP: Ma trận tương quan giữa điểm Toán và DH1")
plt.show()

# --- 4. MÔ HÌNH VÀ ĐÁNH GIÁ (Regression Model) ---
# Bài toán: Dùng điểm Toán lớp 12 (T5, T6) làm Input để dự đoán Output là điểm DH1
X = df[['T5', 'T6']]
y = df['DH1']

# Chia tập Train/Test (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Khởi tạo và Huấn luyện (Train) 2 mô hình theo yêu cầu của thầy
lin_reg = LinearRegression()
knn_reg = KNeighborsRegressor(n_neighbors=5)

lin_reg.fit(X_train, y_train)
knn_reg.fit(X_train, y_train)

# Output: Dự đoán trên tập Test
y_pred_lin = lin_reg.predict(X_test)
y_pred_knn = knn_reg.predict(X_test)

# Đánh giá bằng MSE và MAE
print("\n--- ĐÁNH GIÁ MÔ HÌNH ---")
print(f"Linear Regression -> MSE: {mean_squared_error(y_test, y_pred_lin):.4f}, MAE: {mean_absolute_error(y_test, y_pred_lin):.4f}")
print(f"k-NN Regressor    -> MSE: {mean_squared_error(y_test, y_pred_knn):.4f}, MAE: {mean_absolute_error(y_test, y_pred_knn):.4f}")

# Vẽ Đồ thị (graph) so sánh
plt.figure(figsize=(10, 5))
plt.plot(y_test.values, label='Thực tế (Ground Truth)', marker='o', linestyle='dashed', color='black')
plt.plot(y_pred_lin, label='Dự đoán (Linear Regression)', marker='x', color='blue')
plt.plot(y_pred_knn, label='Dự đoán (k-NN)', marker='s', color='orange')
plt.title("Graph: So sánh Kết quả Dự đoán DH1")
plt.legend()
plt.show()

"""# Mục mới

# Mục mới
"""