# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BO-Ysp-NcQlcYRZMmXNRRWzf9tHDDB6T
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Đọc file dữ liệu (chú ý tên file phải đúng với file bạn đã upload)
df = pd.read_csv('dulieuxettuyendaihoc.csv')

# Xem nhanh 5 dòng đầu
display(df.head())

# Kiểm tra tổng số lượng dữ liệu bị thiếu ở từng cột
print(df.isnull().sum())

# Điền khuyết dữ liệu cột DT bằng giá trị 0
df['DT'] = df['DT'].fillna(0)
# Kiểm tra lại xem còn thiếu không
print("Sau khi xử lý, số dòng thiếu của DT:", df['DT'].isnull().sum())

# Ví dụ: Vẽ Boxplot cho cột điểm khối thi DH1, DH2, DH3 để tìm outlier
plt.figure(figsize=(10, 5))
sns.boxplot(data=df[['DH1', 'DH2', 'DH3']])
plt.title("Biểu đồ Boxplot cho các điểm thi đại học")
plt.show()

# Lấy các cột dữ liệu là số
numeric_cols = df.select_dtypes(include=[np.number]).columns

# Loại trừ cột STT (Số thứ tự) và DT (Dân tộc) ra khỏi việc quét outlier
cols_to_check = [col for col in numeric_cols if col not in ['STT', 'DT']]

for col in cols_to_check:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Lọc bỏ các dòng chứa giá trị nằm ngoài khoảng an toàn
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print("Số lượng dòng còn lại sau khi loại bỏ outlier:", df.shape[0])

# Kiểm tra phân bố của biến Giới tính (GT) và Khối thi (KT)
fig, ax = plt.subplots(1, 2, figsize=(12, 4))
sns.countplot(x='GT', data=df, ax=ax[0])
ax[0].set_title("Phân bố Giới tính (GT)")

sns.countplot(x='KT', data=df, ax=ax[1])
ax[1].set_title("Phân bố Khối thi (KT)")

plt.show()

print("Số lượng đếm từng Khối thi:\n", df['KT'].value_counts())

# 1. Đổi Giới tính (GT): F (Nữ) -> 0, M (Nam) -> 1 bằng Label Encoding
df['GT'] = df['GT'].map({'F': 0, 'M': 1})

# 2. Đổi Khu vực (KV) và Khối thi (KT) bằng One-Hot Encoding
# (Vì các hạng mục này không có tính thứ bậc lớn bé)
df = pd.get_dummies(df, columns=['KV', 'KT'], drop_first=False)

# Chuyển đổi các cột True/False sinh ra từ get_dummies về 0/1 (int)
for col in df.columns:
    if df[col].dtype == bool:
        df[col] = df[col].astype(int)

# Xem thành quả cuối cùng
display(df.head())

"""----------------------------------------------------------"""

